kino/kino_app/routes/auth.py
from flask import Blueprint, request, redirect, url_for, flash
from flask_login import login_user, logout_user
from utils import get_db_connection
from kino_app.models.auth_model import *

auth = Blueprint('auth', __name__)


class User:
    id = None
    login = None
    registration_date = None

    def load_from_db(self, user_id):
        conn = get_db_connection()
        db_record = try_get_user_data_by_id(conn, user_id)
        self.id = int(db_record['user_id'])
        self.login = str(db_record['user_login'])
        self.registration_date = int(db_record['registration_date'])
        return self

    def create(self, user_data):
        self.id = int(user_data['user_id'])
        self.login = str(user_data['user_login'])
        self.registration_date = int(user_data['registration_date'])
        return self

    @property
    def is_active(self):
        return True

    @property
    def is_authenticated(self):
        return self.is_active

    @property
    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    def __str__(self):
        return f'{self.id}:{self.login}'


@auth.route('/login', methods=['POST'])
def login():
    conn = get_db_connection()
    username = request.form.get('username')
    password = request.form.get('password')
    rememberme = bool(request.form.get('rememberme'))
    user_data = try_get_user_data(conn, username, password)
    if user_data is not None:
        login_user(User().create(user_data), rememberme)
    else:
        flash('Incorrect username or password')
        # if incorrect login -> go to full login page
        # https://flask.palletsprojects.com/en/0.12.x/patterns/flashing/
    return redirect(request.referrer)


@auth.route('/logout', methods=['POST'])
def logout():
    logout_user()
    return redirect(url_for('main.main_page'))


@auth.route('/signup', methods=['POST'])
def signup():
    conn = get_db_connection()
    username = request.form.get('username')
    password = request.form.get('password')
    password_again = request.form.get('password_again')
    if password != password_again or len(password) == 0:
        return redirect(request.referrer)
    try_create_user(conn, username, password)
    user_data = try_get_user_data(conn, username, password)
    if user_data is not None:
        login_user(User().create(user_data), True)
    return redirect(request.referrer)

kino/kino_app/routes/main_route.py
import pandas as pd
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user

from kino_app import visit_count
from utils import get_db_connection
from kino_app.models.kino_model import *

main = Blueprint('main', __name__)


@main.route('/')
def main_page():
    conn = get_db_connection()

    username = current_user.login if current_user.is_authenticated else None
    movies = get_user_list(conn, username)
    reviews = get_movie_recent_reviews(conn, 7)
    popular = get_popular_today(conn)

    html = render_template(
        'main.html',
        movies=movies,
        reviews=reviews,
        popular=popular,
        len=len,
        range=range,
        notna=pd.notna
    )
    return html


@main.route('/gallery')
def gallery():
    conn = get_db_connection()
    search_query = request.args.get('search_query')
    search_query = search_query.strip() if search_query is not None else ""
    selected_genre = request.args.get('genre_select')
    selected_genre = selected_genre if selected_genre is not None else -1

    movies = get_filtered_movies(conn, search_query, selected_genre)
    genres = get_genres(conn)

    html = render_template(
        'gallery.html',
        movies=movies,
        genres=genres,
        search_query=search_query,
        selected_genre=selected_genre,
        len=len,
        range=range,
        int=int,
        notna=pd.notna
    )
    return html


@login_required
@main.route('/list')
def user_list():
    conn = get_db_connection()

    username = current_user.login
    movies = get_user_list(conn, username, True)

    html = render_template(
        'user_list.html',
        movies=movies,
        len=len,
        range=range,
        notna=pd.notna
    )
    return html


@login_required
@main.route('/add/review', methods=['POST'])
def edit_or_add_review():
    conn = get_db_connection()

    username = current_user.login
    movie_id = request.form.get('movie_id')
    score = request.form.get('rating-10')
    status_id = request.form.get('status')
    text = request.form.get('text')
    text = text if len(text) > 0 else None
    old_review = get_user_review(conn, username, movie_id)
    old_text = old_review['review'] if old_review is not None else None

    if text is None or text == old_text:
        update_list_entry(conn, username, movie_id, status_id, score)
    else:
        add_or_edit_review(conn, username, movie_id, status_id, score, text)

    update_movies_rating(conn)

    return redirect(request.referrer)


@main.route('/movie/<int:movie_id>')
def movie_page(movie_id):
    add_visit(movie_id)
    conn = get_db_connection()

    username = current_user.login if current_user.is_authenticated else None
    movie = get_movie(conn, movie_id)
    genres = get_movie_genres(conn, movie_id)
    crew = get_movie_crew(conn, movie_id)
    crew_by_roles = {role: [(person_id, person_name) for i, person_name, r, person_id in crew.itertuples() if r == role]
                     for role in list(crew['crew_role_name'])}
    reviews = get_movie_reviews(conn, movie_id, 7)
    user_review = get_user_review(conn, username, movie_id)

    html = render_template(
        'movie.html',
        movie=movie.loc[0],
        genres=genres,
        crew=crew_by_roles,
        reviews=reviews,
        user_review=user_review,
        len=len,
        range=range,
        notna=pd.notna,
        none=None
    )
    return html


def add_visit(movie_id):
    if movie_id in visit_count.keys():
        visit_count[movie_id] += 1
    else:
        visit_count[movie_id] = 1

kino/kino_app/templates/base.html
<!DOCTYPE html>
<html lang="en" data-theme="halloween" class="bg-base-300">
<head>
    <title> {% block title %} Название {% endblock %} </title>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/main.css') }}"/>
    <link rel="stylesheet" href=../static/css/films_styles.css>
    <link rel="icon" href="../static/img/bocchi.png">
    {% import "macros.html" as macros %}
</head>
<body>

<div id="navbar" class="transition-transform navbar fixed top-0 z-50 bg-base-100 md:px-20">
    <div class="navbar-start">
        <a class="btn btn-ghost normal-case text-xl px-10" href={{ url_for("main.main_page") }}>
            KinoMachine
        </a>
    </div>
    <div class="navbar-center flex">
        <ul class="menu menu-horizontal p-0">
            <li><a href={{ url_for("main.gallery") }}>Gallery</a></li>
            {% if current_user.is_authenticated %}
                <li><a href={{ url_for("main.user_list") }}> My List </a></li>
            {% else %}
                <li><a> My List </a></li>
            {% endif %}
            <li><a>Rating</a></li>
        </ul>
    </div>
    <div class="navbar-end">
        {% if current_user.is_authenticated %}
            <div class="dropdown dropdown-hover dropdown-bottom dropdown-end">
                <label tabindex="0" class="text-primary text-xl mx-6">{{ current_user.login }}</label>
                <form class="dropdown-content menu p-4 shadow bg-base-100 rounded-box pt-5" tabindex="0"
                      action="{{ url_for('auth.logout') }}" method="post">
                    <input type="submit" id="logout" class="btn btn-outline btn-primary min-h-0 h-9 mx-1"
                           value="Log Out"/>
                </form>
            </div>
        {% else %}
            <a id="signup" class="btn btn-outline btn-primary min-h-0 h-9 mx-1">Sign Up</a>
            <a id="login" class="btn btn-primary min-h-0 h-9 mx-1">Log In</a>
        {% endif %}
    </div>
</div>

<div class="main">
    {% block main %}
    {% endblock %}
</div>

<dialog class="popup rounded-2xl" id="login-popup">
    <div class="w-full h-full p-0" id="popup-body">
        <form action="{{ url_for('auth.login') }}" class="flex flex-col max-w-4xl max-h-96 mx-24" method="post">
            <div class="normal-case text-xl text-center mt-16">Enter account</div>
            <div class="flex flex-col gap-4 my-7">

                <label>
                    <input name="username" class="input input-bordered input-primary w-64" type="text"
                           placeholder="Username..."/>
                </label>
                <label>
                    <input name="password" class="input input-bordered input-primary w-64" type="password"
                           placeholder="Password..."/>
                </label>
                <div class="form-control">
                    <label class="label cursor-pointer">
                        <span class="label-text">Remember me</span>
                        <input name="rememberme" type="checkbox" class="checkbox checkbox-primary"/>
                    </label>
                </div>
            </div>

            <button class="btn btn-wide mb-2 mb-16" type="submit">Login</button>
        </form>
    </div>

</dialog>
<dialog class="popup rounded-2xl" id="signup-popup">
    <div class="w-full h-full p-0" id="signup-popup-body">
        <form action="{{ url_for('auth.signup') }}" class="flex flex-col max-w-4xl max-h-96 mx-24" method="post">
            <div class="normal-case text-xl text-center mt-16">Create account</div>
            <div class="flex flex-col gap-4 my-7">

                <label>
                    <input name="username" class="input input-bordered input-primary w-64" type="text"
                           placeholder="Username..."/>
                </label>
                <label>
                    <input name="password" class="input input-bordered input-primary w-64" type="password"
                           placeholder="Password..."/>
                </label>
                <label>
                    <input name="password_again" class="input input-bordered input-primary w-64" type="password"
                           placeholder="Password again..."/>
                </label>
            </div>

            <button class="btn btn-wide mb-2 mb-16" type="submit">Join the site!</button>
        </form>
    </div>

</dialog>
</body>
<script src="../static/scripts.js"></script>
</html>

kino/kino_app/templates/films_template.html
{% extends "base.html" %}

{% block title %} Gallery {% endblock %}

{% block main %}
    <div class="flex flex-wrap justify-around">
        {% for i in range(len(movies)) %}
            {{ macros.render_movie(movies.loc[i], notna) }}
        {% endfor %}
    </div>
{% endblock %}

kino/kino_app/templates/gallery.html
{% extends "base.html" %}

{% block title %} Gallery {% endblock %}

{% block main %}
    <div class="flex flex-col w-full">
        <form action="{{ url_for("main.gallery") }}" method="get" class="flex flex-row rounded-xl w-fit self-center mt-4 bg-base-100 p-2 gap-4">

            <input name="search_query" type="text" placeholder="Title, person or description..."
                   class="input input-bordered input-primary w-96" value="{{ search_query }}"/>

            <select name="genre_select" class="select select-primary w-36">
                <option {% if int(selected_genre) == -1 %} selected {% endif %} value="-1">
                        Any genre
                </option>
                {% for i in range(len(genres)) %}
                    <option {% if i == int(selected_genre) %} selected {% endif %} value="{{ i }}">
                        {{ genres.loc[i]['genre_name'] }}
                    </option>
                {% endfor %}
            </select>

            <input class="btn btn-outline btn-primary self-end" type="submit" value="Search">
        </form>

        <div class="flex flex-wrap justify-around pt-4 w-fit">
            {% for i in range(len(movies)) %}
                <div class="mx-2">
                    {{ macros.render_movie(movies.loc[i], notna) }}
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

kino/kino_app/templates/main.html
{% extends "base.html" %}

{% block title %} KinoMachine {% endblock %}

{% block main %}
    <div class="flex flex-col w-full border-opacity-100">
        <div class="w-full mb-5">
            <img class="" src="../static/img/hp.png" alt="Гарри Поттер">
        </div>

        {% if current_user.is_authenticated %}
            <div class="divider font-bold text-2xl px-10">Your list</div>
            <div class="carousel py-3 w-full">
                {% for i in range(len(movies)) %}
                    <div class="carousel-item mx-2">
                        {{ macros.render_small_movie(movies.loc[i], notna) }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        <div class="divider font-bold text-2xl px-10">Popular today</div>
        <div class="carousel py-3 w-full">
            {% for i in range(len(popular)) %}
                <div class="carousel-item mx-2" >
                    {{ macros.render_movie(popular.loc[i], notna) }}
                </div>
            {% endfor %}
        </div>

        <div class="divider font-bold text-2xl px-10">Latest reviews</div>
        <div class="carousel py-3 w-full">
            {% for i in range(len(reviews)) %}
                <div class="carousel-item mx-2" >
                    {{ macros.render_review_card(len, reviews.loc[i]) }}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

kino/kino_app/templates/movie.html
{% extends "base.html" %}

{% block title %} {{ movie['movie_name'] }} {% endblock %}

{% block main %}
    <div class="w-full flex justify-center pt-5 flex-col">
        <div class="flex flex-row self-center max-w-3xl mb-16">
            <img class="rounded-xl shadow-lg mx-3 self-start" src="{{ movie['movie_poster_url'] }}"
                 alt="{{ movie['movie_name'] }}">
            <div class="flex flex-col px-5">
                <div class="mb-5">
                    <h1 class="font-extrabold text-5xl mb-2">{{ movie['movie_name'] }}</h1>
                    <h2 class="font-bold text-xl">
                        ({{ movie['movie_type_name'] }} {{ movie['movie_release_year'] }})</h2>
                </div>
                {% if notna(movie['movie_rating']) %}
                    {{ macros.render_disable_rating(movie['movie_rating'] // 1, 'rating-calculated') }}
                {% endif %}

                <p class="mb-5">{{ movie['movie_description'] }}</p>


                <div class="grid grid-cols-4 gap-2">

                    <p class="font-bold">Duration</p>
                    {% set hours = movie['movie_duration_minutes'] //  60 %}
                    {% if hours > 0 %}
                        <p class="col-span-3">{{ hours }}h {{ movie['movie_duration_minutes'] % 60 }}m</p>
                    {% else %}
                        <p class="col-span-3">{{ movie['movie_duration_minutes'] % 60 }}m</p>
                    {% endif %}

                    <p class="font-bold">Genres</p>
                    <p class="col-span-3">
                        {% set genre_count = len(genres) %}
                        {% for i in range(genre_count - 1) %}
                            <a> {{ genres.loc[i]['genre_name'] }}</a>,
                        {% endfor %}
                        <a>
                            {{ genres.loc[genre_count - 1]['genre_name'] }}
                        </a>
                    </p>
                    {% for crew_role in crew %}
                        <p class="font-bold">{{ crew_role }}</p>
                        <p class="col-span-3">
                            {% set role_count = len(crew[crew_role]) %}
                            {% for i in range(role_count - 1) %}
                                <a> {{ crew[crew_role][i][1] }}</a>,
                            {% endfor %}
                            <a>
                                {{ crew[crew_role][role_count - 1][1] }}
                            </a>
                        </p>
                    {% endfor %}

                </div>

            </div>
        </div>

        <div class="flex flex-col self-center max-w-3xl mb-16">
            {% if current_user.is_authenticated %}
                <div class="divider font-bold text-2xl px-10">Your review</div>
                {% if user_review is not none %}
                    <div class="flex flex-row mt-2">
                        <div class="font-bold text-xl mx-3">
                            {{ user_review['status_name'] }}
                        </div>
                        {{ macros.render_disable_rating(user_review['user_list_movie_rating']) }}
                    </div>
                    <p class="mb-5">
                        {% if user_review['review'] != none %}
                            {{ user_review['review'] }}
                        {% endif %}
                    </p>
                    <label for="edit-review" class="btn btn-outline btn-primary">Edit</label>
                {% else %}
                    <label for="edit-review" class="btn btn-outline btn-primary">Add</label>
                {% endif %}
            {% endif %}
            {% if len(reviews) > 0 %}
                <div class="divider font-bold text-2xl px-10 mt-7">Latest reviews</div>
                {% for i in range(len(reviews)) %}
                    <div class="mx-2 my-3 self-center">
                        {{ macros.render_small_review_card(len, reviews.loc[i]) }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <input type="checkbox" id="edit-review" class="modal-toggle"/>
    <div class="modal">
        {% if user_review is not none %}
            <form class="modal-box" action="{{ url_for("main.edit_or_add_review") }}" method="post">
                <input type="hidden" name="movie_id" value="{{ movie['movie_id'] }}">
                <h3 class="font-bold text-lg">Edit Review</h3>
                <div class="flex flex-col">
                    <select name="status" class="select w-40 mt-3 mb-1">
                        <option {% if user_review['status_id'] == 0 %} selected {% endif %} value="0">Completed
                        </option>
                        <option {% if user_review['status_id'] == 1 %} selected {% endif %} value="1">Watching
                        </option>
                        <option  {% if user_review['status_id'] == 2 %} selected {% endif %} value="2">Plan to Watch
                        </option>
                        <option  {% if user_review['status_id'] == 3 %} selected {% endif %} value="3">Dropped
                        </option>
                    </select>
                    <div class="px-3">
                        {{ macros.render_rating(user_review['user_list_movie_rating']) }}
                    </div>
                    <label>
                        {% if user_review['review'] != none %}
                            {% set old_text = user_review['review'] %}
                        {% else %}
                            {% set old_text = "" %}
                        {% endif %}
                        <textarea name="text" class="textarea textarea-warning w-full h-52"
                                  placeholder="Describe your impressions...">{{ old_text }}</textarea>
                    </label>
                </div>
                <div class="flex flex-row modal-action">
                    <input class="btn btn-primary" type="submit" value="Save">
                    <label for="edit-review" class="btn btn-outline btn-primary">Cancel</label>
                </div>
            </form>
        {% else %}
            <form class="modal-box" action="{{ url_for("main.edit_or_add_review") }}" method="post">
                <input type="hidden" name="movie_id" value="{{ movie['movie_id'] }}">
                <h3 class="font-bold text-lg">Add Review</h3>
                <div class="flex flex-col">
                    <select name="status" class="select w-40 mt-3 mb-1">
                        <option value="0">Completed</option>
                        <option value="1">Watching</option>
                        <option value="2">Plan to Watch</option>
                        <option value="3">Dropped</option>
                    </select>
                    <div class="px-3">
                        {{ macros.render_rating(0) }}
                    </div>
                    <label>
                    <textarea name="text" class="textarea textarea-warning w-full h-52"
                              placeholder="Describe your impressions..."></textarea>
                    </label>
                </div>
                <div class="flex flex-row modal-action">
                    <input class="btn btn-primary" type="submit" value="Save">
                    <label for="edit-review" class="btn btn-outline btn-primary">Cancel</label>
                </div>
            </form>
        {% endif %}
    </div>

{% endblock %}

kino/kino_app/templates/user_list.html
{% extends "base.html" %}

{% block title %} {{ current_user.login }} {% endblock %}

{% block main %}
    {#    <div class="w-full flex justify-center pt-5 flex-col">#}
    <div class="w-full flex justify-center items-center pt-5 flex-col">

        <h1 class="font-extrabold text-5xl mb-7">{{ current_user.login }} list</h1>

        <div class="overflow-x-auto w-3/5">
            <table class="table w-full">
                <thead>
                <tr>
                    <th></th>
                    <th class="">Title</th>
                    <th class="w-1/5">Score</th>
                    <th class="w-1/5">Status</th>
                </tr>
                </thead>

                <tbody>

                {% for i in range(len(movies)) %}
                    <tr class="hover">
                        <th>{{ i + 1 }}</th>
                        <td><a href="/movie/{{ movies.loc[i]['movie_id'] }}">{{ movies.loc[i]['movie_name'] }}</a></td>
                        {% if notna(movies.loc[i]['user_list_movie_rating']) %}
                            <td>
                                <label class="card_link cursor-pointer" for="ul{{ movies.loc[i]['movie_id'] }}">
                                    {{ movies.loc[i]['user_list_movie_rating'] }}
                                </label>
                            </td>
                        {% else %}
                            <td>
                                <label class="cursor-pointer" for="ul{{ movies.loc[i]['movie_id'] }}">
                                    —
                                </label>
                            </td>
                        {% endif %}
                        {% if notna(movies.loc[i]['status_name']) %}
                            <td>
                                <label class="card_link cursor-pointer" for="ul{{ movies.loc[i]['movie_id'] }}">
                                    {{ movies.loc[i]['status_name'] }}
                                </label>
                            </td>
                        {% else %}
                            <td>
                                <label class="cursor-pointer" for="ul{{ movies.loc[i]['movie_id'] }}">
                                    —
                                </label>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

    {% for i in range(len(movies)) %}
        <input type="checkbox" id="ul{{ movies.loc[i]['movie_id'] }}" class="modal-toggle"/>
        <div class="modal">
            <form class="modal-box w-64" action="{{ url_for("main.edit_or_add_review") }}" method="post">
                <input type="hidden" name="movie_id" value="{{ movies.loc[i]['movie_id'] }}">
                <h3 class="font-bold text-lg">{{ movies.loc[i]['movie_name'] }}</h3>
                <div class="flex flex-col">
                    <select name="status" class="select w-40 mt-3 mb-1">
                        <option {% if movies.loc[i]['status_id'] == 0 %} selected {% endif %} value="0">
                            Completed
                        </option>
                        <option {% if movies.loc[i]['status_id'] == 1 %} selected {% endif %} value="1">
                            Watching
                        </option>
                        <option {% if movies.loc[i]['status_id'] == 2 %} selected {% endif %} value="2">
                            Plan to Watch
                        </option>
                        <option {% if movies.loc[i]['status_id'] == 3 %} selected {% endif %} value="3">
                            Dropped
                        </option>
                    </select>
                    <div class="px-3">
                        {{ macros.render_rating(movies.loc[i]['user_list_movie_rating']) }}
                    </div>
                </div>
                <div class="flex flex-row modal-action">
                    <input class="btn btn-primary" type="submit" value="Save">
                    <label for="ul{{ movies.loc[i]['movie_id'] }}"
                           class="btn btn-outline btn-primary">Cancel</label>
                </div>
            </form>
        </div>
    {% endfor %}

{% endblock %}